/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PreviewRouteImport } from './routes/preview'
import { Route as EditRouteImport } from './routes/edit'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EditNewRouteImport } from './routes/edit.new'
import { Route as EditWishIdRouteImport } from './routes/edit.$wishId'

const PreviewRoute = PreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const EditRoute = EditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditNewRoute = EditNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => EditRoute,
} as any)
const EditWishIdRoute = EditWishIdRouteImport.update({
  id: '/$wishId',
  path: '/$wishId',
  getParentRoute: () => EditRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/edit': typeof EditRouteWithChildren
  '/preview': typeof PreviewRoute
  '/edit/$wishId': typeof EditWishIdRoute
  '/edit/new': typeof EditNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/edit': typeof EditRouteWithChildren
  '/preview': typeof PreviewRoute
  '/edit/$wishId': typeof EditWishIdRoute
  '/edit/new': typeof EditNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/edit': typeof EditRouteWithChildren
  '/preview': typeof PreviewRoute
  '/edit/$wishId': typeof EditWishIdRoute
  '/edit/new': typeof EditNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/edit' | '/preview' | '/edit/$wishId' | '/edit/new'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/edit' | '/preview' | '/edit/$wishId' | '/edit/new'
  id: '__root__' | '/' | '/edit' | '/preview' | '/edit/$wishId' | '/edit/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EditRoute: typeof EditRouteWithChildren
  PreviewRoute: typeof PreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/preview': {
      id: '/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof PreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit': {
      id: '/edit'
      path: '/edit'
      fullPath: '/edit'
      preLoaderRoute: typeof EditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit/new': {
      id: '/edit/new'
      path: '/new'
      fullPath: '/edit/new'
      preLoaderRoute: typeof EditNewRouteImport
      parentRoute: typeof EditRoute
    }
    '/edit/$wishId': {
      id: '/edit/$wishId'
      path: '/$wishId'
      fullPath: '/edit/$wishId'
      preLoaderRoute: typeof EditWishIdRouteImport
      parentRoute: typeof EditRoute
    }
  }
}

interface EditRouteChildren {
  EditWishIdRoute: typeof EditWishIdRoute
  EditNewRoute: typeof EditNewRoute
}

const EditRouteChildren: EditRouteChildren = {
  EditWishIdRoute: EditWishIdRoute,
  EditNewRoute: EditNewRoute,
}

const EditRouteWithChildren = EditRoute._addFileChildren(EditRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EditRoute: EditRouteWithChildren,
  PreviewRoute: PreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
